'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace _1714bWaller2H

    Partial Public Class Design
        Public Property Id As Integer
        Public Property FName As String
        Public Property LName As String
        Public Property Phone As String
    
        Public Overridable Property SkateShop As SkateShop
        Public Overridable Property Skates As ICollection(Of Skate) = New HashSet(Of Skate)
        Public Overridable Property CustomBoards As ICollection(Of CustomBoard) = New HashSet(Of CustomBoard)
    
    End Class

End Namespace
