'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace _1714bWaller2H

    Partial Public Class SkateShopModelContainer
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=SkateShopModelContainer")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property Skates() As DbSet(Of Skate)
        Public Overridable Property SkateShops() As DbSet(Of SkateShop)
        Public Overridable Property Designs() As DbSet(Of Design)
        Public Overridable Property CustomBoards() As DbSet(Of CustomBoard)
        Public Overridable Property Invoices() As DbSet(Of Invoice)
        Public Overridable Property LineItems() As DbSet(Of LineItem)
    
    End Class

End Namespace
