'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace _1714bWaller2H

    Partial Public Class Skate
        Public Property Id As Integer
        Public Property FName As String
        Public Property LName As String
        Public Property Phone As String
    
        Public Overridable Property SkateShop As SkateShop
        Public Overridable Property Design As Design
    
    End Class

End Namespace
