'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace _1714bwaller2G

    Partial Public Class Building
        Public Property Id As Integer
        Public Property BuildingName As String
        Public Property Address As String
        Public Property City As String
        Public Property State As String
        Public Property Zip As String
    
        Public Overridable Property Apartments As ICollection(Of Apartment) = New HashSet(Of Apartment)
    
    End Class

End Namespace
