'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace _1714bwaller2G

    Partial Public Class LineItem
        Public Property Id As Integer
        Public Property Description As String
        Public Property Amount As Decimal
    
        Public Overridable Property Invoice As Invoice
    
    End Class

End Namespace
