'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace _1714bwaller2G

    Partial Public Class Person
        Public Property Id As Integer
        Public Property FirstName As String
        Public Property LastName As String
        Public Property Phone As String
        Public Property Email As String
    
        Public Overridable Property Apartments As ICollection(Of Apartment) = New HashSet(Of Apartment)
        Public Overridable Property Apartments1 As ICollection(Of Apartment) = New HashSet(Of Apartment)
    
    End Class

End Namespace
