'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace _1754bWaller2F

    Partial Public Class Animal
        Public Property Id As Integer
        Public Property AnimalName As String
        Public Property BirthDate As Date
        Public Property Description As String
    
        Public Overridable Property AnimalType As AnimalType
        Public Overridable Property Person As Person
    
    End Class

End Namespace
