'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace _1754bWaller2F

    Partial Public Class DonationTypes
        Public Property Id As Integer
        Public Property Description As String
    
        Public Overridable Property Donations As Donation
    
    End Class

End Namespace
