'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace _1754bWaller2F

    Partial Public Class Person
        Public Property Id As Integer
        Public Property Title As String
        Public Property FirstName As String
        Public Property LastName As String
        Public Property Phone As String
    
        Public Overridable Property Animals As ICollection(Of Animal) = New HashSet(Of Animal)
        Public Overridable Property Donations As ICollection(Of Donation) = New HashSet(Of Donation)
    
    End Class

End Namespace
